#!/usr/bin/env python3
#
# Doofish Set
#
import sys, os, re, time, random, collections, itertools, functools
def read_int(): a = input().split(); return int(a[0]) if len(a) == 1 else [int(x) for x in a]
N, M = read_int()
g = [[] for _ in range(N)]
for _ in range(M):
	a, b = read_int()
	g[a - 1].append(b - 1)
	g[b - 1].append(a - 1)

for u in range(N):
	g[u] = (sorted(g[u]), u);
g = sorted(g)

p = -1
z = dict()
for i in range(N):
	u = g[i][1]
	if i == 0 or g[i][0] != g[i - 1][0]:
		z[u] = [u]
		p = u
	else:
		z[p].append(u)
n = len(z)
m = 0
v = []
for i, x in z.items():
	v.append(x)
	m += len(x) * (N - len(x))

m //= 2
if m == M:
	k = 1
	ans = []
	while k < n:
		t = ("1" * k + "0" * k) * (N // (2 * k) + 1)
		t = t[:n]
		s = [' '] * N
		for i, c in enumerate(t):
			for p in v[i]: s[p] = c
		ans.append(''.join(s))
		k *= 2
	print(len(ans))
	print("\n".join(ans))
else:
	print(-1)
